{% set name = "mockupdb" %}
{% set version = "1.8.1" %}
{% set sha256 = "d36d0e5b6445ff9141e34d012fa2b5dfe589847aa1e3ecb8d774074962af944e" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  # No mongodb on s390x
  skip: True  # [py<34 or s390x]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pymongo >=3

test:
  source_files:
    - tests
  imports:
    - mockupdb
  requires:
    # Add a constraint of pymongo<4 as the tests use functions removed
    # in pymongo 4.0
    - pymongo >=3,<4  # [not (py>311 or (py>310 and osx and arm64) )]
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests  # [not (py>311 or (py>310 and osx and arm64) )]

about:
  home: https://github.com/ajdavis/mongo-mockup-db
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MongoDB Wire Protocol server library
  description: |
    Mock server for testing MongoDB clients and creating MongoDB Wire
    Protocol servers.
  doc_url: https://mockupdb.readthedocs.io/
  dev_url: https://github.com/ajdavis/mongo-mockup-db

extra:
  recipe-maintainers:
    - hodgsonw
