travis:
  secure:
    BINSTAR_TOKEN: mYeod8OUjdUo6OHhfYlhnkxwVQt75A80NRgmByLGhZBsKATDgB2GrW4FzcKJ2hDJHhEaRfDQsDklzObX0530FI7z2i2o1PWVsCEaQvLx2h1kH0cnOlqiW9hCVeCIBiFfe79qHc1SShCQWKFctrGqUZtsH6BJZsxR67/QkdX1daHo8DP8tb58+Z970wrYZ+Fqt4WbKc0kRr96sjKFSbY7/9Q4AIMQtb3QDtEcvkLsVGVnrzzDP0k92KZJ3V7W6WGll4nf1JL4We2EALSGJFw7y2VzPfL+rkkr5rTjllJDK2In/21pOXDc01M8L3j0ITCzwz9dD5uCzzLGDChHRP99FDylIAIKvZft7AypCaXnj49VYuIE+KMxl6sCwHFmqTBZe7hda8lBj6Zij5GzPaN9wUmybIk5k9lE9IUuC9LMdLaec7zSoiPCwwxc5Km+9vVGn/Akr8ilXrFL/NTxx+DCCifLE+gmgpvPmwprMdMZk6Erbtcnr7ioPL3QwRPWtYpLk3ysDRuaJe4N9tXDxpU3WfI3vb0qoCrjkIiPhDVDczFd+2LZZ8a/hPEpSQbckqyCkHZHECGpDeehDI4G6XtgoSV7wrw8HIMK/dsSvx4QObLtd6zCVc/WMjWhlbDI+2FaacUGoXMP7X1LZMuqrtYU2fXrazjJEe1ls5C2exijLV8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
